[package]
name = "rebar"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies.reqwest]
version = "0.11.9"
features = ["blocking"]

[dev-dependencies.http]
version = "0.2.6"